name: Clubium CI Build

on:
  push:
    branches: ['**']
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build and test
        run: |
          sbt clean scalafmtCheck test
